### ISSUE TITLE
Need help to install

### ISSUE THREAD

**Issue by nilskt** [dingusdk/ha-dukaone#1]
This looks great. I have Blauberg fans, and I think this is the same fan as Duka. Please look at this documentation: https://blaubergventilatoren.de/uploads/download/b133_4_1en_01preview.pdf

Edit: looks like it works great with Blauberg Expert v2

Regards,

Nils

**Comment by dingusdk** [comment]
Thanks for the documentation - I think it is the same! (Could have saved me a lot of time)

To add a duka one to Home assistant go to configuration|Integrations and click the "+" in the lower right corner. Then find the "Duka One" in the list. In the dialog enter a name for the device and the device id. You can find the device id in the mobile app for Duka One. If you know the IP of the device you can enter it. Or you can enter the broardcast address of your subnet (like 192.168.0.255). You can also leave it empty and the integration will try to broadcast and find the device. (Note this does not always works - depending on you network and Home Assistant setup).

I have also added the above to the readme.

Let me know if it is working so I can add the Blauberg fan as compatible.

**Comment by nilskt** [comment]
Thanks a lot! Yeah it works perfectly with Blauberg Expert v2 fans. And I guess it is also compatible with Vents Twinfresh v.2 and Flexit Roomie One v2. They are all the same.

Also thanks for the configuration instructions (I am a Home Assistant newbe :-) ). Maybe you also can give some more details how to install the entity row you made?

**Comment by dingusdk** [comment]
I have added more help to the readme:

https://github.com/dingusdk/duka-control-entity-row
