### ISSUE TITLE
[Feeature request] Allow switching "mode"

### ISSUE THREAD

**Issue by Aephir** [dingusdk/ha-dukaone#10]
Thanks for the integration!

I noticed a few times that my ventilator had switched from "Varmegenvindings funktion" to "Ventilationsfunktion". Would it be possible to add a switch or service call to set this?

**Comment by allanedk** [comment]
+1

**Comment by dingusdk** [comment]
It is already there as a service call: 

dukaone.set_mode

**Comment by Aephir** [comment]
Thanks! Looking forward to the docker version being updated :)
