### ISSUE TITLE
Polymer is not defined 

### ISSUE THREAD

**Issue by clavdal** [dingusdk/ha-dukaone#11]
Hi 
Im getting this in my dashboard.

<img width="482" alt="image" src="https://github.com/dingusdk/ha-dukaone/assets/83058870/c7cf3f18-a880-480c-b566-2f9596492db2">

And see this log in my log files 
Logger: frontend.js.latest.202307051 
Source: components/system_log/__init__.py:257 
First occurred: 12 July 2023 at 18:58:07 (5 occurrences) 
Last logged: 09:19:06 
•	https://ha.domain.dk/hacsfiles/duka-control-entity-row/duka-control-entity-row.js:2:32 Uncaught ReferenceError: Polymer is not defined 
•	http://ha.domain.dk:8123/hacsfiles/duka-control-entity-row/duka-control-entity-row.js:2:39 ReferenceError: Can't find variable: Polymer 
•	https://ha.domain.dk/hacsfiles/duka-control-entity-row/duka-control-entity-row.js:2:39 ReferenceError: Can't find variable: Polymer

I have found this regarding the error
Polymer and Lit are programming frameworks, making writing Javascript easier. Polymer was recently deprecated in HA. If a card still uses Polymer, it needs to be rewritten to use Lit or plain Javascript instead.

**Comment by dingusdk** [comment]
This is an issue for the [front end](https://github.com/dingusdk/duka-control-entity-row).
It is already there so i will close this one
