### ISSUE TITLE
Issues in having multiple device on the same network

### ISSUE THREAD

**Issue by MikkelFrid** [dingusdk/ha-dukaone#13]
Thank you for a great integration. 

I have been having issues adding two devices on the same network. 
I have suddenly got it to work, but I am still not entirely sure how.

From what I can debug, also using the locale PY library with the example, something is faulty when the device password is set.
When I added my first device, I could easily do it using "1111", but when I tried with the second device, no passwords worked. 
This resultet in the error "Failed to setupup dukaone device". 

The only thing I could do to get it to work, was to change the files config_flow.py and fan.py from "1111" to "1112" and do the same on the second device, suddenly it worked. 

I have no clue if this is a caching error, the password not being assigned correctly or something completely different.

**Comment by dingusdk** [comment]
Please update to 2024.1.0 and verify if you still have the issue

**Comment by dingusdk** [comment]
I will close this issue, if it is still not working for you with the newest version, then open a new isssue again.
