### ISSUE TITLE
Duka One S 4 wifi

### ISSUE THREAD

**Issue by been65** [dingusdk/ha-dukaone#14]
Hi
Thanks for the Great integration on my S4 wifi i  cant chance the flow on the fan, i only have two entities in HA, power and fan speed and humidity.
Hope you Can fix that?

**Comment by garret** [comment]
@been65 I am considering to buy the S6 wifi model but maybe also the S4 for the "washing machine/bathroom" room. Did you manage in the end to control the fan speed of your S4 with this HA integration?

**Comment by been65** [comment]
Hi Garret
Is i am able to turn it on/off, set the humidity and set speed but i am not able to switch between the three methods for ventilations. It would have been fine but it works for me now.

**Comment by mholst** [comment]
I would also like to thank you for creating this awesome integration. I have two Duka 6S Wifi  in the house, which are displayed in Homeassistant and can be set to a custom speed and toggled on/off.

I am fairly new to home assistant, and this integration is one of the reasons why I am testing out HA. I have been using openHAB for ages, but they do seem to loose traction on new tech, and also lack this integration.

I would also like to state that I am also unable to control the modes, and resetting the filter. It might be obvious to experienced users, but I am not there yet.

Any help/examples would be awesome.

Again thanks for your great work.

**Comment by mholst** [comment]
Just a short follow up.
Finally made the switch from openHAB to Homeassistant.
I just followed your description on how to do the reset functionality by button press, which works like a dream on my two Duka One 6S Wifi.

Thank you.
