### ISSUE TITLE
Issues with ventilators running synced still a problem

### ISSUE THREAD

**Issue by allanedk** [dingusdk/ha-dukaone#16]
In reference to this one #12

Sorry to keep bothering you, @dingusdk. But this issue still remains and I hope you can guide me in the right direction.

I have tried to remove the fan (=2 fans running as one) and add it again. The latest error message is:

`Logger: custom_components.dukaone.sensor
Source: custom_components/dukaone/sensor.py:32
Integration: Duka One ([documentation](https://github.com/dingusdk/ha-dukaone))
First occurred: 16:17:47 (8 occurrences)
Last logged: 22:17:35
Failed to setup dukaone device`

Apparently **sensor.py:32** is this check failing:
`if not await dukaonesensor.wait_for_device_to_be_ready():
    _LOGGER.error("Failed to setup dukaone device")
    return False`

Any idea to what I can do?

I also see this one, as mentioned in the other issue:

`Platform dukaone does not generate unique IDs. ID 0034004C42435718 already exists`

PS: Thanks a lot for working on this integration and sharing it! Much appreciated!

**Comment by dingusdk** [comment]
Sorry for the late answer, I don't have my duka's synced (they are not in the same room, and in different floors).

The error is if the duka one device does not send an answer back. The network communication is done by sending a broadcast on the network, and the duka one device also send their status as broardcast every 1 sec.
So if your network is setup in a way where broardcast is not passed it will not work.
If you are running you HA from docker in windows it will probably not work. (It run fine from docker in linux - that is how i run it)
Hope this can help you

**Comment by allanedk** [comment]
Thanks! 

For some reason, it started working again. I just noticed it after your reply here. Don't know why and what changed, but it works now.
