### ISSUE TITLE
Is it possible to set speed as an integer?

### ISSUE THREAD

**Issue by cmartin81** [dingusdk/ha-dukaone#2]
I have noticed that you can set the speed from high, medium and low. I know that high is usually 80%, sometimes I need to set it to 100% is this possible?
Is it also possible to mute the sound (The fan makes a beep/sound every time it receives a command)?

Thanks for making the plugin! I'm using it for a Twinfresh fan

**Comment by nilskt** [comment]
I would like to adjust the speed manually (It is possible in the native app). The documentation does not describe how to disable sound, but when adjusting speed manually in the app (not the preset speeds), there is no beep. Lets hope Jens (@dingusdk) is looking into this!

**Comment by cmartin81** [comment]
Yes, that is true. So If @dingusdk can support setting the speed with an integer it will solve everything! :) It is very annoying when the fan beeps all the time. The fan is in my living room and it also wakes up my family when it is beeping.

**Comment by dingusdk** [comment]
I assumed the high speed was 100%, but you are right, it is less. I have not been using the manual speed, and have not implemented it in the library for the fan. It was a long process extracting the communication with the fan so i just did a minimum. I will look into this, when I get some time for it (read be patient)

**Comment by cmartin81** [comment]
Thanks for answering! For what it is worth I have a copy of the manual where you will find everything you need to know regarding the communication between the fan and your api :) That way you do not need to reverse engineering the signals. 
https://github.com/cmartin81/twinfresh-api/blob/master/src/b133_4_1en_01preview.pdf
This manual is for the twinfresh fan, but I believe they use the same signals. Since your code is working with my fans :)

**Comment by cmartin81** [comment]
Honestly I do not think it will be a lot of code, unfortunately I do not have a lot of experience with python nor writing plugins for Home Assistant. Are there anything I can do to help you implement the last bit of code?

**Comment by dingusdk** [comment]
Thanks for the  api doc - i did already get it from another user, and it helps a lot - I whish I had this when i started.

**Comment by dingusdk** [comment]
Manual speed now in the version 1.0.0 just released.  NOte you cannot set the manual speed from th UI - it does not look like the defaultt HA fan UI has support for it. You can set it with a service function

**Comment by cmartin81** [comment]
Santa just came early this year 🎅🎅🎅 
Thank you very much! I'll test it right away!

**Comment by cmartin81** [comment]
I can confirm that it works great! And also without any "beep" 🙏
Minor thing is that your GUI is now broken when using manual speed. (not a big issue for me)
<img width="556" alt="Overview_-_Home_Assistant" src="https://user-images.githubusercontent.com/510413/102892334-01a3e700-4460-11eb-85ab-ae60f1186ad6.png">
