### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by frnyb** [dingusdk/ha-dukaone#22]
Thanks for great work! Will this integration work with a Duka One 50+ WiFi? I'm considering buying that one. Cheers!

**Comment by dingusdk** [comment]
I assume it will work, but I don't know, I can only test the model I have: Duka S6W.
If you want to know of that exact model - it is probably better to ask in the Home Assistant forum

**Comment by frnyb** [comment]
Thanks for the answer. I will get it and test it and provide results.
