### ISSUE TITLE
Detected blocking call inside the event loop

### ISSUE THREAD

**Issue by MikOsle** [dingusdk/ha-dukaone#3]
Hi,

I'm getting following error

Logger: homeassistant.util.async_
Source: util/async_.py:144
First occurred: 22:35:53 (60 occurrences)
Last logged: 22:35:59

Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for dukaone doing blocking calls at custom_components/dukaone/sensor.py, line 98: "model": f"Type {self.device.unit_type}",
Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for dukaone doing blocking calls at custom_components/dukaone/sensor.py, line 99: "sw_version": f"{self.device.firmware_version} {self.device.firmware_date}",

version | core-2022.2.5
host_os | Home Assistant OS 7.4
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9

**Comment by dingusdk** [comment]
The newest version 1.0.6 should fix this.
