### ISSUE TITLE
NoneType has no attribute 'speed'

### ISSUE THREAD

**Issue by Aephir** [dingusdk/ha-dukaone#5]
First off, thanks a lot for making this. I've been hassling the Duka App dev team for years for them to open their API after they hinted they would (but they have no immediate plans for that as of May 9th, 2022).

I have installed this integration via HACS, and set up my three Duka One units. They connect, and show up but I cannot control them. I keep getting this error when trying to control the `fan.duka_xxx`. Regardless of whether I try to toggle on/off or select a `preset mode`, it shows

<img width="504" alt="Screenshot 2022-05-11 at 19 29 06" src="https://user-images.githubusercontent.com/20152788/167911607-575e325b-91b0-4d2d-b1b8-89d4696e1eb6.png">

Though of course showing a different "service", if that's what I call (e.g. `Failed to call service fan/set_preset_mode...` if trying that instead of toggling on/off, but it's always `... has no attribute 'speed'`).

Any idea what's wrong? The sensor (humidity) seems to work fine for each unit. As does reporting of the fan, if I manually turn off, it shows immediately in Hass as a state change to `fan.duka_xxx`

HassOS v7.6
HassCore v2022.5.3
Duka integrationo v1.0.6

**Comment by Aephir** [comment]
Oh no! In my excitement over the entities and status showing up, I completely forgot to restart Hass after installing.

So sensors work without reboot, control needs the reboot. 

Thanks again, and sorry for the confusion!

**Comment by BirgerKo** [comment]
The API is completely disclosed from Blauberg which seems to be the
original manufacturer of these units.
https://blaubergventilatoren.de/uploads/download/b133_4_1en_01preview.pdf

/Birger

ons. 11. mai 2022 kl. 20:25 skrev Aephir ***@***.***>:
