### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by SinnoTech** [dingusdk/ha-dukaone#6]
What entities are exposed by the duka 1?

**Comment by dingusdk** [comment]
Each duka will show as a device in HA with 2 entities - a fan and a sensor (humidity)

**Comment by HotBlack77** [comment]
Is there any way to expose the fan speen and fan mode (e.g. in, out or out-then-in)? Maybe even the filter alarm?
It seems to me that the underlying API supports them, or am I mistaken?

**Comment by dingusdk** [comment]
All of them is already there as attributes in HA

**Comment by HotBlack77** [comment]
> All of them is already there as attributes in HA
> 

Yes, discovered that 10 mins after I posted. Thanks for all your amazing work.
