### ISSUE TITLE
Blauberg VENTO Expert A50-1 W v1 support?

### ISSUE THREAD

**Issue by kondrikserg** [dingusdk/ha-dukaone#8]
This API supports the Blauberg VENTO Expert A50-1 W v1 ? 
If not, is it possible to extend the support to support this device with the ability to manually control the speed in percentages? 
The device API supports manual speed control and there are Python libraries that allow it.

**Comment by spwtit** [comment]
@kondrikserg I'm using it with Blauberg fans. Though I'm not sure about the exact model. The only thing that seems to be working for me is on/off and reading the humidity.
@gody01 was/is working on another version [here](https://github.com/gody01/ecovent_v2). I don't know if it supports v1 devices though.
